# Generated by Django 3.2.13 on 2022-06-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('name_ro', models.CharField(max_length=240)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('name', models.CharField(max_length=240)),
                ('name_ro', models.CharField(max_length=240)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='api.bootcamp')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('name_ro', models.CharField(max_length=240)),
                ('bio', models.CharField(max_length=240)),
                ('bio_ro', models.CharField(max_length=240)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('name_ro', models.CharField(max_length=240)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.cohort')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.instructor')),
                ('topics', models.ManyToManyField(to='api.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='cohort',
            name='instructors',
            field=models.ManyToManyField(related_name='cohorts', through='api.Role', to='api.Instructor'),
        ),
    ]
